version: '3.4'

services:
  simpleapi:
    image: simpleapi
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      mode: replicated
      replicas: 5
    networks:
      - simpleapi-network
    ports:
      - "23480"

  simpleapi-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simpleapi
    ports:
      - "11011:11011"
    networks:
      - simpleapi-network

networks:
  simpleapi-network: